title: airscript.it
email: hello@airscript.it
description: >-
  Sharing happiness with code!
baseurl: ""
url: ""
twitter_username: airscript
github_username:  airscripts

theme: minima
plugins:
  - jekyll-feed
